# Generates the input file in the right order for KWN model
import sys
import yaml


test_name=sys.argv[1]
a_yaml_file = open('{s}/input.yaml'.format(s=test_name))
parsed_yaml_file = yaml.load(a_yaml_file, Loader=yaml.FullLoader)




with open('input.dat', 'w') as f:
		f.write( "'%s' \n" % test_name)
		f.write( "%.3e \n" % parsed_yaml_file['kwn_step0'])
		f.write( "%.3e \n" % parsed_yaml_file['kwn_stepsize'])
		f.write( "%d \n" % parsed_yaml_file['kwn_nsteps'])
		f.write( "%f \n" % parsed_yaml_file['T'])
		f.write( "%.3e \n" % parsed_yaml_file['strain_rate'])
		f.write( "%.1e \n" % parsed_yaml_file['lattice_parameter'])
		f.write( "%.1e \n" % parsed_yaml_file['atomic_volume'])
		f.write( "%.1e \n" % parsed_yaml_file['molar_volume'])
		f.write( "%.1e \n" % parsed_yaml_file['misfit_energy'])
		f.write( "%.3f \n" % parsed_yaml_file['gamma_coherent'])
		f.write( "%.4e \n" % parsed_yaml_file['solute_diffusion0'][0])
		f.write( "%.4e \n" % parsed_yaml_file['solute_diffusion0'][1])
		f.write( "%.4e \n" % parsed_yaml_file['solute_migration_energy'][0])
		f.write( "%.4e \n" % parsed_yaml_file['solute_migration_energy'][1])
		f.write( "%.4e \n" % parsed_yaml_file['c0_matrix'][0])
		f.write( "%.4e \n" % parsed_yaml_file['c0_matrix'][1])
		f.write( "%.d \n" % parsed_yaml_file['stoichiometry'][0])
		f.write( "%.d \n" % parsed_yaml_file['stoichiometry'][1])
		f.write( "%.d \n" % parsed_yaml_file['stoichiometry'][2])
		f.write( "%.3e \n" % parsed_yaml_file['vacancy_sink_spacing'])
		f.write( "%.3e \n" % parsed_yaml_file['vacancy_diffusion0'])
		f.write( "%.3e \n" % parsed_yaml_file['jog_formation_energy'])
		f.write( "%.3e \n" % parsed_yaml_file['activation_energy_pipe_diffusion'])
		f.write( "%.3e \n" % parsed_yaml_file['vacancy_formation_energy'])
		f.write( "%.3e \n" % parsed_yaml_file['vacancy_migration_energy'])
		f.write( "%.3e \n" % parsed_yaml_file['dislocation_arrangement'])
		f.write( "%.3e \n" % parsed_yaml_file['vacancy_generation'])
		f.write( "%.3e \n" % parsed_yaml_file['initial_dislocation_density'])
		f.write( "%.3e \n" % parsed_yaml_file['saturation_dislocation_density'])
		f.write( "%.4e \n" % parsed_yaml_file['burgers_vector'])
		f.write( "%.4e \n" % parsed_yaml_file['initial_mean_radius'])
		f.write( "%.4e \n" % parsed_yaml_file['initial_volume_fraction'])
		f.write( "%.4e \n" % parsed_yaml_file['dispersion_parameter'])
		f.write( "%.4e \n" % parsed_yaml_file['time'])
		f.write( "%.4e \n" % parsed_yaml_file['dt_max'])
		f.write( "%.4e \n" % parsed_yaml_file['output_time_step'])
		f.write( "%.4e \n" % parsed_yaml_file['sigma_r'])
		f.write( "%.4e \n" % parsed_yaml_file['A'])
		f.write( "%.4e \n" % parsed_yaml_file['Q_stress'])
		f.write( "%.4e \n" % parsed_yaml_file['n'])
		f.write( "%.4e \n" % parsed_yaml_file['c_eq'][0])
		f.write( "%.4e \n" % parsed_yaml_file['c_eq'][1])
		f.write( "%.d \n" % parsed_yaml_file['incubation'])

with open('input.namelist', 'w') as f:
		f.write( "&config\n" )
		f.write( f"testfolder = '{test_name}' \n")
		f.write( f"kwn_step0 = {parsed_yaml_file['kwn_step0']:.3e} \n")
		f.write( f"kwn_stepsize = {parsed_yaml_file['kwn_stepsize']:.3e} \n")
		f.write( f"kwn_nsteps = {parsed_yaml_file['kwn_nsteps']:d} \n")
		f.write( f"Temperature = {parsed_yaml_file['T']:f} \n")
		f.write( f"strain_rate = {parsed_yaml_file['strain_rate']:.3e} \n")
		f.write( f"lattice_param = {parsed_yaml_file['lattice_parameter']:.1e} \n")
		f.write( f"atomic_volume = {parsed_yaml_file['atomic_volume']:.1e} \n")
		f.write( f"molar_volume = {parsed_yaml_file['molar_volume']:.1e} \n")
		f.write( f"misfit_energy = {parsed_yaml_file['misfit_energy']:.1e} \n")
		f.write( f"gamma_coherent = {parsed_yaml_file['gamma_coherent']:.3f} \n")
		f.write( f"diffusion0 = {parsed_yaml_file['solute_diffusion0'][0]:.4e}, {parsed_yaml_file['solute_diffusion0'][1]:.4e} \n")
		f.write( f"migration_energy = {parsed_yaml_file['solute_migration_energy'][0]:.4e}, {parsed_yaml_file['solute_migration_energy'][1]:.4e} \n")
		f.write( f"c0_matrix = {parsed_yaml_file['c0_matrix'][0]:.4e}, {parsed_yaml_file['c0_matrix'][1]:.4e} \n")
		f.write( f"stoechiometry = {parsed_yaml_file['stoichiometry'][0]:d}, {parsed_yaml_file['stoichiometry'][1]:d}, {parsed_yaml_file['stoichiometry'][2]:d} \n")
		f.write( f"vacancy_sink_spacing = {parsed_yaml_file['vacancy_sink_spacing']:.3e} \n")
		f.write( f"vacancy_diffusion0 = {parsed_yaml_file['vacancy_diffusion0']:.3e} \n")
		f.write( f"jog_formation_energy = {parsed_yaml_file['jog_formation_energy']:.3e} \n")
		f.write( f"q_dislocation = {parsed_yaml_file['activation_energy_pipe_diffusion']:.3e} \n")
		f.write( f"vacancy_energy = {parsed_yaml_file['vacancy_formation_energy']:.3e} \n")
		f.write( f"vacancy_migration_energy= {parsed_yaml_file['vacancy_migration_energy']:.3e} \n")
		f.write( f"dislocation_arrangement = {parsed_yaml_file['dislocation_arrangement']:.3e} \n")
		f.write( f"vacancy_generation = {parsed_yaml_file['vacancy_generation']:.3e} \n")
		f.write( f"rho_0 = {parsed_yaml_file['initial_dislocation_density']:.3e} \n")
		f.write( f"rho_s = {parsed_yaml_file['saturation_dislocation_density']:.3e} \n")
		f.write( f"burgers = {parsed_yaml_file['burgers_vector']:.4e} \n")
		f.write( f"mean_radius_initial = {parsed_yaml_file['initial_mean_radius']:.4e} \n")
		f.write( f"volume_fraction_initial = {parsed_yaml_file['initial_volume_fraction']:.4e} \n")
		f.write( f"shape_parameter = {parsed_yaml_file['dispersion_parameter']:.4e} \n")
		f.write( f"total_time = {parsed_yaml_file['time']:.4e} \n")
		f.write( f"dt_max = {parsed_yaml_file['dt_max']:.4e} \n")
		f.write( f"time_record_step = {parsed_yaml_file['output_time_step']:.4e} \n")
		f.write( f"sigma_r = {parsed_yaml_file['sigma_r']:.4e} \n")
		f.write( f"A = {parsed_yaml_file['A']:.4e} \n")
		f.write( f"Q_stress = {parsed_yaml_file['Q_stress']:.4e} \n")
		f.write( f"n = {parsed_yaml_file['n']:.4e} \n")
		f.write( f"ceq_matrix = {parsed_yaml_file['c_eq'][0]:.4e}, {parsed_yaml_file['c_eq'][1]:.4e} \n")
		f.write( f"incubation = {parsed_yaml_file['incubation']:.4e} \n")
		f.write( f"/\n" )